#------------------
# Wikipedia Top 100
#    If you want to translate the charts on top.hatnote.com, start with a copy
#    of this file and leave us a note at:
#    https://github.com/hatnote/top/issues
#------------------------------------------------------------------------------

#-----------
# Page title
#------------------------------------------------------------------------------

title: ଲୋକପ୍ରିୟ ୧୦୦
full_title: >-
  ଓଡ଼ିଆ ଉଇକିପିଡ଼ିଆର ଲୋକପ୍ରିୟ ୧୦୦ ପ୍ରସଙ୍ଗ {formatted_date}

index_title: >-
  ଓଡ଼ିଆ ଉଇକିପିଡ଼ିଆର ଲୋକପ୍ରିୟ ୧୦୦ ପ୍ରସଙ୍ଗ

rss_title: >-
  ଓଡ଼ିଆ ଉଇକିପିଡ଼ିଆ'ର ଲୋକପ୍ରିୟ ୧୦୦ ପ୍ରସଙ୍ଗ

wikipedia: ଉଇକିପିଡ଼ିଆ
language_project: ଓଡ଼ିଆ ଉଇକିପିଡ଼ିଆ
tagline: >-
    The most-visited English Wikipedia articles, updated daily. <a
    href="#about" class="learn">Learn more</a>...

alt_tagline: >-
    The most-visited English Wikipedia articles, updated daily.

#------
# Links
#------------------------------------------------------------------------------

about_link: About
more_langs_link: More languages
feed_link: Feed
blog_link: Blog
top: Back to top 

#---------
# Articles
#
#   Each article has statistics at the bottom like this:
#   934.8K views (↑300.5K from yesterday)
#------------------------------------------------------------------------------

views: views
from_yesterday: from yesterday
streak: day streak

#------------
# About section
#------------------------------------------------------------------------------

about_header: About
about_section: >-
     <p>Read the <a href="http://top.hatnote.com/en/wikipedia">archive</a>.</p>

     <p>A daily list of the most visited Wikipedia articles, generated
     by <a href="https://twitter.com/sklaporte">Stephen LaPorte</a>
     and <a href="https://twitter.com/mhashemi">Mahmoud
     Hashemi</a>. It's also available in <a
     href="http://top.hatnote.com/about.html">more languages</a>. If
     you find this list interesting, you will enjoy <a
     href="http://weekly.hatnote.com">The Weeklypedia</a>, a weekly
     digest of the most edited Wikipedia articles. Learn more on the <a
     href="#">Hatnote Blog</a>.</p>

     <p>This page was made possible by <a
     href="https://wikimedia.org/api/rest_v1/?doc#!/Pageviews_data/get_metrics_\
     pageviews_top_project_access_year_month_day">Wikipedia's new page
     view API</a>, with some nice images and summaries from the <a
     href="https://www.mediawiki.org/wiki/API:Query">MediaWiki
     API</a>. You can find more code and documentation <a
     href="https://github.com/hatnote/top">available on
     github</a>.</p>

     <p>Want to see a list of the most visited articles in another
     language of Wikipedia? So do we! Please <a
     href="https://github.com/hatnote/top/issues">send a request</a>
     and let us know if you can help translate the templates.</p>

     <p><a href="https://twitter.com/hatnotable">@hatnotable</a></p>

#------- 
# Tweets 
#
#   We can provide three possible tweets. They shouldn't be longer than 117 
#   characters (including the article title, so there is enough space to 
#   include a link.
#------------------------------------------------------------------------------

long_tweet: >- 
    On a {streak}-day streak, {title} was the #{rank} most
    read article on #{project} w/ {views} views

medium_tweet: "{title} was viewed {views} times on #{project}"
short_tweet: "{title} was #{rank} on #{project}"

#-------------
# Archive page
#------------------------------------------------------------------------------

all_traffic_data: All traffic data

#----
# RSS
#------------------------------------------------------------------------------

rss_intro: The new English Wikipedia numbers are in!
rss_description: >-
    <a href="{permalink|s}">{title}</a> came in at #{rank}, with {views_short} 
    views{?streak_min}, continuing its {streak_len}-day streak on the chart 
    ({view_trend|s}{view_delta} views since yesterday){/streak_min}.

rss_read_more: Read more...
